export PATH=$HOME/.toolbox/bin:$PATH
export TERM='xterm-256color'
export MY_SCRIPTS=~/dotfiles/shell
export EDITOR='nvim'
setopt +o nomatch

export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm




##//extend-cli begin

# Path to your oh-my-zsh installation.
export EXTEND_CLI="/Users/connorjerow/.extend-cli"

# Setup the alias
alias ec="yarn --silent --cwd $EXTEND_CLI run extend-cli"

# User configuration
export AWS_DEFAULT_PROFILE=partnerssandbox

source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
bindkey '^ ' autosuggest-accept

source $MY_SCRIPTS/scripts.sh
source $MY_SCRIPTS/prompt.sh
#source $MY_SCRIPTS/base16.sh

##//extend-cli end
