export PATH=$HOME/.toolbox/bin:$PATH
export MY_SCRIPTS=~/dotfiles/shell
export EDITOR='nvim'
export TERM=xterm-16color
setopt +o nomatch

export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm


##//extend-cli begin

# Path to your oh-my-zsh installation.
export EXTEND_CLI="/Users/connorjerow/.extend-cli"

# Setup the alias
alias ec="yarn --silent --cwd $EXTEND_CLI run extend-cli"

# User configuration
export AWS_DEFAULT_PROFILE=partnerssandbox



source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
bindkey '^ ' autosuggest-accept
autoload -Uz compinit && compinit -i # completion such as git branches


source $MY_SCRIPTS/scripts.sh
source $MY_SCRIPTS/prompt.sh
source ${HOMEBREW_PREFIX}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

##//extend-cli end
