""" Vundle Plugin Manager
	set nocompatible              " be iMproved, required
	filetype off                  " required

	" set the runtime path to include Vundle and initialize
	set rtp+=~/.vim/bundle/Vundle.vim
	call vundle#begin()
	Plugin 'VundleVim/Vundle.vim'
	Plugin 'scrooloose/nerdtree'
	Plugin 'vim-airline/vim-airline'
	Plugin 'tpope/vim-fugitive'
	Plugin 'tpope/vim-surround'
	Plugin 'chriskempson/base16-vim'
	call vundle#end()            " required


""" Utilitarianisms
	syntax on

	set encoding=utf8
	let base16colorspace=256
	set t_Co=256
	source ~/.vim/colorscheme.vim
	
	set wrap " turn on line wrapping
	set wrapmargin=8 " wrap lines when comeing within n characters from side
	set linebreak           " Break line at full word
	set showbreak=...       " show eliipsis at breaking

	set autoindent
	set smartindent
	set foldmethod=syntax



	set showcmd		" Show (partial) command in status line.

	set number		" Show line number
	set relativenumber	" Have relative numbers from cur line

	set showmatch		" Show matching brackets.

	set ignorecase		" Do case insensitive matching
	set hlsearch		" Highlight matches for search 


""" Custom Mappings
	let mapleader = "," " map leader to comma
	map <C-j> 3<C-E>
	map <C-k> 3<C-Y>


""" NERDTree
	let NERDTreeShowHidden=1    " Show hidden files in NERDTree
